image: python:3.11-slim

stages:
  - build

pages:
  stage: build
  script:
    - mkdir -p public
    - python scripts/fetch_essays.py --feed https://chrisnwoko.substack.com/feed --out public/essays.json || echo "fetch failed, using committed essays.json if present"
    - cp index.html public/index.html
    - cp -f essays.json public/essays.json || true
    # Debug: show what's in public/ before publishing
    - echo "Contents of public/ directory:"
    - ls -la public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"
  # Run daily at 2 AM UTC to fetch new posts
  schedule:
    - cron: "0 2 * * *"
